/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */
package io.github.bhuwanupadhyay.schemas;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class PaymentRequested extends org.apache.avro.specific.SpecificRecordBase
    implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7646654175546204286L;
  public static final org.apache.avro.Schema SCHEMA$ =
      new org.apache.avro.Schema.Parser()
          .parse(
              "{\"type\":\"record\",\"name\":\"PaymentRequested\",\"namespace\":\"io.github.bhuwanupadhyay.schemas\",\"fields\":[{\"name\":\"orderId\",\"type\":\"string\"},{\"name\":\"totalAmount\",\"type\":\"string\"}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PaymentRequested> ENCODER =
      new BinaryMessageEncoder<PaymentRequested>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PaymentRequested> DECODER =
      new BinaryMessageDecoder<PaymentRequested>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   *
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PaymentRequested> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   *
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PaymentRequested> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link
   * SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PaymentRequested> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PaymentRequested>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PaymentRequested to a ByteBuffer.
   *
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PaymentRequested from a ByteBuffer.
   *
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PaymentRequested instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of
   *     this class
   */
  public static PaymentRequested fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence orderId;
  @Deprecated public java.lang.CharSequence totalAmount;

  /**
   * Default constructor. Note that this does not initialize fields to their default values from the
   * schema. If that is desired then one should use <code>newBuilder()</code>.
   */
  public PaymentRequested() {}

  /**
   * All-args constructor.
   *
   * @param orderId The new value for orderId
   * @param totalAmount The new value for totalAmount
   */
  public PaymentRequested(java.lang.CharSequence orderId, java.lang.CharSequence totalAmount) {
    this.orderId = orderId;
    this.totalAmount = totalAmount;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return orderId;
      case 1:
        return totalAmount;
      default:
        throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        orderId = (java.lang.CharSequence) value$;
        break;
      case 1:
        totalAmount = (java.lang.CharSequence) value$;
        break;
      default:
        throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   *
   * @return The value of the 'orderId' field.
   */
  public java.lang.CharSequence getOrderId() {
    return orderId;
  }

  /**
   * Sets the value of the 'orderId' field.
   *
   * @param value the value to set.
   */
  public void setOrderId(java.lang.CharSequence value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'totalAmount' field.
   *
   * @return The value of the 'totalAmount' field.
   */
  public java.lang.CharSequence getTotalAmount() {
    return totalAmount;
  }

  /**
   * Sets the value of the 'totalAmount' field.
   *
   * @param value the value to set.
   */
  public void setTotalAmount(java.lang.CharSequence value) {
    this.totalAmount = value;
  }

  /**
   * Creates a new PaymentRequested RecordBuilder.
   *
   * @return A new PaymentRequested RecordBuilder
   */
  public static io.github.bhuwanupadhyay.schemas.PaymentRequested.Builder newBuilder() {
    return new io.github.bhuwanupadhyay.schemas.PaymentRequested.Builder();
  }

  /**
   * Creates a new PaymentRequested RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new PaymentRequested RecordBuilder
   */
  public static io.github.bhuwanupadhyay.schemas.PaymentRequested.Builder newBuilder(
      io.github.bhuwanupadhyay.schemas.PaymentRequested.Builder other) {
    if (other == null) {
      return new io.github.bhuwanupadhyay.schemas.PaymentRequested.Builder();
    } else {
      return new io.github.bhuwanupadhyay.schemas.PaymentRequested.Builder(other);
    }
  }

  /**
   * Creates a new PaymentRequested RecordBuilder by copying an existing PaymentRequested instance.
   *
   * @param other The existing instance to copy.
   * @return A new PaymentRequested RecordBuilder
   */
  public static io.github.bhuwanupadhyay.schemas.PaymentRequested.Builder newBuilder(
      io.github.bhuwanupadhyay.schemas.PaymentRequested other) {
    if (other == null) {
      return new io.github.bhuwanupadhyay.schemas.PaymentRequested.Builder();
    } else {
      return new io.github.bhuwanupadhyay.schemas.PaymentRequested.Builder(other);
    }
  }

  /** RecordBuilder for PaymentRequested instances. */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder
      extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentRequested>
      implements org.apache.avro.data.RecordBuilder<PaymentRequested> {

    private java.lang.CharSequence orderId;
    private java.lang.CharSequence totalAmount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(io.github.bhuwanupadhyay.schemas.PaymentRequested.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.totalAmount)) {
        this.totalAmount = data().deepCopy(fields()[1].schema(), other.totalAmount);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing PaymentRequested instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(io.github.bhuwanupadhyay.schemas.PaymentRequested other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.totalAmount)) {
        this.totalAmount = data().deepCopy(fields()[1].schema(), other.totalAmount);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Gets the value of the 'orderId' field.
     *
     * @return The value.
     */
    public java.lang.CharSequence getOrderId() {
      return orderId;
    }

    /**
     * Sets the value of the 'orderId' field.
     *
     * @param value The value of 'orderId'.
     * @return This builder.
     */
    public io.github.bhuwanupadhyay.schemas.PaymentRequested.Builder setOrderId(
        java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'orderId' field has been set.
     *
     * @return True if the 'orderId' field has been set, false otherwise.
     */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }

    /**
     * Clears the value of the 'orderId' field.
     *
     * @return This builder.
     */
    public io.github.bhuwanupadhyay.schemas.PaymentRequested.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'totalAmount' field.
     *
     * @return The value.
     */
    public java.lang.CharSequence getTotalAmount() {
      return totalAmount;
    }

    /**
     * Sets the value of the 'totalAmount' field.
     *
     * @param value The value of 'totalAmount'.
     * @return This builder.
     */
    public io.github.bhuwanupadhyay.schemas.PaymentRequested.Builder setTotalAmount(
        java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.totalAmount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'totalAmount' field has been set.
     *
     * @return True if the 'totalAmount' field has been set, false otherwise.
     */
    public boolean hasTotalAmount() {
      return fieldSetFlags()[1];
    }

    /**
     * Clears the value of the 'totalAmount' field.
     *
     * @return This builder.
     */
    public io.github.bhuwanupadhyay.schemas.PaymentRequested.Builder clearTotalAmount() {
      totalAmount = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PaymentRequested build() {
      try {
        PaymentRequested record = new PaymentRequested();
        record.orderId =
            fieldSetFlags()[0] ? this.orderId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.totalAmount =
            fieldSetFlags()[1]
                ? this.totalAmount
                : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PaymentRequested> WRITER$ =
      (org.apache.avro.io.DatumWriter<PaymentRequested>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PaymentRequested> READER$ =
      (org.apache.avro.io.DatumReader<PaymentRequested>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override
  protected boolean hasCustomCoders() {
    return true;
  }

  @Override
  public void customEncode(org.apache.avro.io.Encoder out) throws java.io.IOException {
    out.writeString(this.orderId);

    out.writeString(this.totalAmount);
  }

  @Override
  public void customDecode(org.apache.avro.io.ResolvingDecoder in) throws java.io.IOException {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8) this.orderId : null);

      this.totalAmount =
          in.readString(this.totalAmount instanceof Utf8 ? (Utf8) this.totalAmount : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
          case 0:
            this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8) this.orderId : null);
            break;

          case 1:
            this.totalAmount =
                in.readString(this.totalAmount instanceof Utf8 ? (Utf8) this.totalAmount : null);
            break;

          default:
            throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}
